# Generated by Django 4.2.30 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completion_note_task_next_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Work items', max_length=255),
        ),
    ]
